#include "ttmlToAssConverter.h"
#include "ttml.h"
#include <sstream>
#include <iomanip>
#include <vector>

namespace {
    // ASS subtitle format header using C++11 raw string literal.
    const std::string ASS_HEADER = R"([Script Info]
; Script generated by dantto4k-TS4KASS
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,MS UI Gothic,50,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,10,10,50,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
)";
}

TtmlToAssConverter::TtmlToAssConverter() : header_written_(false) {}

std::string TtmlToAssConverter::formatTime(uint64_t ms) {
    uint64_t cs = (ms % 1000) / 10;
    uint64_t s = (ms / 1000) % 60;
    uint64_t m = (ms / (1000 * 60)) % 60;
    uint64_t h = ms / (1000 * 60 * 60);

    std::stringstream ss;
    ss << h << ":" << std::setfill('0') << std::setw(2) << m << ":" << std::setfill('0') << std::setw(2) << s << "." << std::setfill('0') << std::setw(2) << cs;
    return ss.str();
}

std::string TtmlToAssConverter::convert(const std::string_view& ttmlInput) {
    const TTML ttml = TTMLPaser::parse(std::string(ttmlInput));
    std::stringstream assOutput;

    if (!header_written_) {
        assOutput << ASS_HEADER;
        header_written_ = true;
    }

    for (const auto& div : ttml.divTags) {
        if (!div.begin || !div.end) {
            continue;
        }

        std::string text;
        bool first_p_in_div = true;
        for (const auto& p : div.pTags) {
            if (!first_p_in_div) {
                text.append("\\N");
            }
            for (const auto& span : p.spanTags) {
                text.append(span.text);
            }
            first_p_in_div = false;
        }

        // Replace newline characters with ASS format newline code.
        std::string processed_text;
        for (char c : text) {
            if (c == '\n') {
                processed_text.append("\\N");
            } else {
                processed_text.push_back(c);
            }
        }
        
        assOutput << "Dialogue: 0," << formatTime(*div.begin) << "," << formatTime(*div.end)
                  << ",Default,,0,0,0,," << processed_text << "\n";
    }

    return assOutput.str();
}
